### ISSUE TITLE
How to show notifications on any action (e.g., save or update) in my custom application

### ISSUE THREAD

**Issue by mat-burke** [commercetools/merchant-center-application-kit#1065]
I would like to show pop up notifications on changes such as the Merchant Centers does on content updates.

Are there any pre-build components that would suit my need?

(Related [Support Ticket](https://jira.commercetools.com/browse/SUPPORT-6802))

**Comment by emmenko** [comment]
Yes so a notification system is already pre-built within the app packages. In order to show notifications, you need to dispatch notification actions using the [@commercetools-frontend/actions-global](https://www.npmjs.com/package/@commercetools-frontend/actions-global) package.

There are different type of actions but what you usually need is either `showNotification` and `showApiErrorNotification` (_for errors_).

Those functions are action creators for Redux, so you need to dispatch them using Redux. You can also use the React hooks which handle the dispatching automatically.

Here's an example of using them with React Redux:

```jsx
import * as actions from '@commercetools-frontend/actions-global';
import { DOMAINS } from '@commercetools-frontend/constants';

const MyComponent = props => (
  <button
    onClick={() => {
      props.showNotification({
        kind: 'success',
        domain: DOMAINS.SIDE,
        text: 'This is a notification message'
      })
    }}
  >
    Click me
  </button>
)

export default connect(
  null,
  { showNotification: actions.showNotification }
)(MyComponent)
```

or when using React hooks:


```jsx
import * as actions from '@commercetools-frontend/actions-global';
import { DOMAINS } from '@commercetools-frontend/constants';

const MyComponent = props => {
  const showSuccessNotification = useShowNotification({
    kind: 'success',
    domain: DOMAINS.SIDE,
    text: 'This is a notification message'
  });
  return (
    <button
      onClick={() => {
        showSuccessNotification()
      }}
    >
      Click me
    </button>
  )
}

export default MyComponent;
```

**Comment by emmenko** [comment]
@mat-burke do you still need help with this?

**Comment by mat-burke** [comment]
@emmenko the customer hasn't responded in the support ticket. Please feel free to close the issue, I can reopen it or raise a new one if necessary.

Thx and brgds

**Comment by emmenko** [comment]
Ok thanks, we can keep it open for a bit more, no problem.
