### ISSUE TITLE
I don't see my custom application in menu

### ISSUE THREAD

**Issue by alochowski** [commercetools/merchant-center-application-kit#1075]
I've registered my application in Merchant Center, it was available in menu section, but now disappeared.

Is there something change regarding custom application in Merchant Center?

I can using my application by url but isn't see in menu.

**Comment by amine-benselim** [comment]
do you have a `menu.js` for your custom app? one possible issue is that you have setup permissions for the menu that you do not have. therefore you are not able to see your custom app in the menu section.

**Comment by alochowski** [comment]
Thanks for response.

Now menu appeared again. I didn't change nothing.
Maybe it was a temporary problem.

I don't use `menu.json` file, because as far I know Merchant Center don't read this file on production, this file is only using during developing.

I think this issue can be closed for now.

**Comment by tdeekens** [comment]
That is correct. The menu.js is only needed for local development while is a production setup the menu is loaded from a database as configured. 

I can only think of the configuration needing some time to be applied. As custom app configuration is needed on every load of the app we cache it in our proxy quite aggressively. So that when changed it may take up to 30-60 minutes until the change propagates. We plan to communicate this better in the UI too. 

So given everything was working. Then the config was changed to something false (e.g. false permission). This change was flushed. Then the config was changed again to be fixed. This fix might have taken some time to propagate again. 

Sorry for the inconvenience. Glad it works again.

**Comment by alochowski** [comment]
aa ok, thanks for explanation. 
I will keep in mind this after every load of the app.

No problem and thanks a lot.
