### ISSUE TITLE
Document best practices for dealing with permissions

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1264]
Just so that we don't forget.

**Comment by tdeekens** [comment]
Thanks. I just laughed cause it'll be: what was this about again in 2 weeks? Forgot... :D

**Comment by adnasa** [comment]
can someone elaborate this?
What are we missing in the Authorized doc?

**Comment by tdeekens** [comment]
It's for the public documentation of custom apps so it's another audience. Some parts we can surely reuse.

**Comment by FreddieK** [comment]
This will require quite a bit of thinking and investigation I think. [SUPPORT-7722](https://jira.commercetools.com/browse/SUPPORT-7722) is a good reference for when this is revisited for the complexity. Noting down my thoughts as of now;

The current MC permission system is based on the idea that permissions are tied to workflow within the core apps. One consequence of this is that we don't have permissions for entities etc. that aren't used (e.g. shopping lists), which though would be a prime example of what customers are likely to want to build Custom Applications for, since we don't offer it.

This might even work in our favor, as it's reasonable to think that a customer building their own custom app for managing products (in order to enable their specific workflows etc.) would like to disable the core Product app completely. 

Currently, we allow hiding it from the navigation which is a workaround and 'security by obscurity', since it means a user knowing the URLs could still access it and go outside the workflow that the customer might have intended. The 'better' solution would be if we could revoke access to the core application completely, but still grant the custom application the permissions it needs in order to operate.

**Comment by tdeekens** [comment]
Thanks @FreddieK! All valid points. However, this issue was a bit more narrow in scope. We want to document how to use our permission components exposed through app-kit (react things) and not broaden the topic to items you rightfully mentioned. That would require another step and also careful planning. This will not "just happen" was we all know.
