### ISSUE TITLE
SUPPORT-8506 Can't get the custom app starter application running locally

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1434]
Support has received this ticket.  Customer is unable to launch custom app locally.

Details are in ticket here: https://jira.commercetools.com/browse/SUPPORT-8506

**Comment by tdeekens** [comment]
The goal of opening tickets on GitHub is that developers can search here in regards to previous issues, tips and tricks. Then the amount of internal tickets will reduce as engineers may find similar tickets here in the open on the Open Source code it relates to. Just like Open Source works often times. This will mostly only work if the tickets here are self-contained. They also should not reference our internal ticketing system. I would recommend to either move a discussion here with all prior content or open tickets here earlier. So discussions take place here with all parties involved. A bit similar also to what happens around Open Source SDKs. So that we can build a community and knowledge base here. Recurring things can also be part of a troubleshooting section in the docs additionally. 

As such this ticket does not fulfill any purpose. I would recommend either moving internal discussions and information here or keep the discussion in our internal system. 

Thanks for your help.
