### ISSUE TITLE
SUPPORT-8480 Custom application stuck in loop, getting a message to contact support

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1435]
Support has received a ticket regarding custom app deployment being stuck in a loop.

Details are here:

https://jira.commercetools.com/browse/SUPPORT-8480

**Comment by emmenko** [comment]
Thanks but I'm going to close this as there is already an ongoing discussion in the JIRA ticket.

A couple of remarks though:
- avoid linking to internal JIRA tickets
- if you open an issue here it needs to be self contained, meaning that all the necessary information should be provided here. Otherwise it's not helpful for people that don't have access to the JIRA ticket
- for the future, try not to start any conversation in the JIRA ticket, unless it's necessary. Instead, ask the reporter to open the issue in github. I assume that most the time the issues are reported by developers anyway.

Thanks for the cooperation.
