### ISSUE TITLE
Valid hostnames for JWT key?

### ISSUE THREAD

**Issue by iaindwyer** [commercetools/merchant-center-application-kit#1442]
I'm in the midst of setting up the Proxy to External API process with my external API. In [the documentation](https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api) it says "The validation is performed by using the /.well-known/jwks.json endpoint exposed by the Merchant Center API Gateway." but this only seems to work for the [legacy hostnames](https://docs.commercetools.com/custom-applications/main-concepts/api-gateway#hostnames)

Is there a plan to expand it to the newer hostnames? Calling them "legacy" implies they're going away in the future.

**Comment by emmenko** [comment]
Good point, we haven't changed the values of the `issuer` yet because it would otherwise break other clients using it.

I might have an idea though to be able to support both...I'll get back to you on this.

---

I actually have a question for you, since you are interested in the "Proxy to External API" functionality.
Could you share how do you plan to use the external API and what the use case would be?
I'm also particularly interested in the auth part involved, as we are currently working on this topic and we would love to get more feedback on this.
If you wish, we can continue this conversation in private channels.
Thanks

cc @FreddieK

**Comment by iaindwyer** [comment]
I've emailed you about this question
