### ISSUE TITLE
guidance in deployment of Merchant Center extension in Azure

### ISSUE THREAD

**Issue by ct-jenny** [commercetools/merchant-center-application-kit#1585]
**Couldn't create custom app**

**To Reproduce**
Doing step by step instructions here:
https://docs.commercetools.com/custom-applications/getting-started/installing-a-starter-application

created the custom app
used the below command to generate the production build
yarn mc-scripts build
created the env and header json files.
Ran the below command to generate the index html and other components
mc-scripts compile-html --headers=production-aws.headers.json --config=production-aws.env.json --use-local-assets --transformer=config/transformer-aws.js

created the web app in azure and copied the public folder in azure webroot
https://mc-extn.azurewebsites.net

Configured the url in merchant center extension

After npm start it throws error:
./node_modules/@commercetools-frontend/application-shell/dist/application-shell-index.es.jsModule not found: Can't resolve 'apollo-client/version' in '/dist-to-my-project/v2/custom-order-app/node_modules/@commercetools-frontend/application-shell/dist'

**Comment by nagaraja1982** [comment]
All I need is a instruction guide to deploy the app in azure with required configuration, so that i can be used in CT MC custom application.

I have created the custom app
used the below command to generate the production build
yarn mc-scripts build
I have created the env and header json files.
Ran the below command to generate the index html and other components
mc-scripts compile-html --headers=production-aws.headers.json --config=production-aws.env.json --use-local-assets --transformer=config/transformer-aws.js

I have created the web app in azure and copied the public folder in azure webroot

https://mc-extn.azurewebsites.net

Configured the url in merchant center extension and tried to hit the url and i get 404 error

We configure the lambda in aws we need similar kind of set up for azure.

**Comment by tdeekens** [comment]
Sorry for the delayed response.

Regarding the error:

```text
./node_modules/@commercetools-frontend/application-shell/dist/application-shell-index.es.jsModule not found: Can't resolve 'apollo-client/version' in '/dist-to-my-project/v2/custom-order-app/node_modules/@commercetools-frontend/application-shell/dist'
```

What version of the Merchant Center Application Kit is being used? Can you potentially resolve the issue by updating it's dependencies to the latest version as found [here](https://github.com/commercetools/merchant-center-application-kit/releases).

Regarding the second issue. The 404 would be received if the path is not setup as intended. Moreover, the configuration takes some time to flush through the infrastructure. This is noted somewhere on the documentation. Does this problem still persist?

**Comment by nagaraja1982** [comment]
I have not faced error in building the app.
I have requested for the step doc as like aws

**Comment by tdeekens** [comment]
Sorry for the misunderstanding and thanks for the clarification. We will forward this to the respective team and see what we can do.

**Comment by nagaraja1982** [comment]
I have found the process to deploy the custom app in Azure.
This ticket can be closed.

**Comment by tdeekens** [comment]
If you want to set aside some time to help us write the initial documentation that would be greatly appriciated.
