### ISSUE TITLE
Seeing 403 HTTP status code when opening Custom Application

### ISSUE THREAD

**Issue by briantomkins** [commercetools/merchant-center-application-kit#1607]
custom merchant center application is throwing 403 error while integrating with commercetools

static files are hosted on an s3 bucket.

Headers as per the documentation is also configured.
there are no logs . The first request itself is failing with 403

We are using the default configuration that is shipped with the custom mc application - Our main application is running on AWS ECS
Static files are hosted on a s3 bucket
env.prod is same file which is available on the sample custom mc application
headers.json is also the same file which is part of the sample custom application.
The main application needs to be whitelisted , if you want to access it .

**env.prod:**

NODE_ENV=production
MC_API_URL=https://mc-api.australia-southeast1.gcp.commercetools.com
FRONTEND_HOST=cdn.dev.XXXYYY.com/apps/urp-customer-service/
CDN_URL=https://cdn.dev.XXXYYY.com/apps/urp-customer-service/
MC_ENV=production
MC_PROXY_URL=https://mc.australia-southeast1.gcp.commercetools.com
MC_ACCESS_TOKEN= # for schema introspection
CTP_PROJECT_KEY=dev-XXX-YYY-retail

submitted as: SUPPORT-9253

**Comment by tdeekens** [comment]
Can you share which API call specifically gives the `403` and what the correlation id is if it's one of our APIs?

**Comment by github-aji** [comment]
Hi @tdeekens , this is where we are getting 403 errors.

![image](https://user-images.githubusercontent.com/29443279/85961445-da5ae880-b9ed-11ea-8d9d-1673e181f9c6.png)

**Comment by tdeekens** [comment]
Thanks for the image. We will investigate. Can you ensure that the 403 is not coming from an nginx on your end?

As an additional note: your screenshot contained sensitive information (the access token). I updated the screen shot to restract that information and deleted the comment's revision from GitHub. It's best to not share sensitive information in public.

**Comment by github-aji** [comment]
@tdeekens , Does commercetool makes an initial request to the custom application , when the application is added to commercetools?. 
 When access our custom application,the network tab  only shows the request from custom appllication to merchant center and it is throwing a 403.

Today, we noticed the application is running into redirect loop, whenever we try to access.

**Comment by tdeekens** [comment]
No, there is no initial request made when the Custom Application is configured or re-configured on on our side in the Merchant Center. There is however a delay until any configuration (or reconfiguration) is applied. This is due to caching on our end. This means that not every change on the configuration in the MC takes immediate effect.

The fact that you only see a request from the Merchant Center in the Network Panel (if I understand your question correctly) is due to the fact that we (the MC) act as a proxy to your Custom Appliaction and code hosted there. We essentially forward the request to your code/infrastruture and return the status from it. As we do not have nginx in any part of our infrastructure my suspicion is that the error comes from your infrastructure. Maybe some routing misconfiguration or missing firewall setup (just guessing). There is more on the architecture in our Custom Application documentation if your curious.

Regarding the redirect loop: are you running on a new (e.g. `https://mc.europe-west1.gcp.commercetools.com`) or legacy hostname (e.g. `mc.commercetools.com`)? I would propose to flush the browser caches (local storage and cookies specifically) or login in an Inkognito window to rule out any issues which occur when using new and legacy hostnames.

**Comment by github-aji** [comment]
Hi Tobias,
Just checking if you can provide us a range of ips which we can whitelist at our end . Since we are now on our development environment and we have an existing firewall rule, we should be whitelisting your IP . We did a sample application deployment with vercel and we were able to integrate it with the our merchant center without any issues.
FYI information the merchant center we are using is https://mc.australia-southeast1.gcp.commercetools.com

**Comment by emmenko** [comment]
Hi,

when you develop locally, there is no HTTP proxy involved. You develop the app as-is and for every external domain that your app talk to, you need to list the domains in the `headers.json` file.

https://docs.commercetools.com/custom-applications/deployment/runtime-configuration#headersjson

As for the nginx issue, I assume this happens only on the MC production environment. Is the range of ips the only option you have?

**Comment by github-aji** [comment]
Yes, local development is working fine . When we deploy the custom application in production mode , in our dev environment we are getting this issue . As I said earlier, this might be because of the firewall rules of our organisation. Whitelisting is the range of IPs is the only option, available at our end.

**Comment by github-aji** [comment]
@emmenko ,
The redirect loop issue got fixed when I updated the servedByProxy to false.

**Comment by emmenko** [comment]
The `servedByProxy` needs to be set to `true` on production.

**Comment by emmenko** [comment]
> As I said earlier, this might be because of the firewall rules of our organisation.

Can I ask what's the reason for putting strict firewall rules on a bunch of static files?

> Whitelisting is the range of IPs is the only option, available at our end.

If that's the only option, we will see what we can offer you, but I can't promise anything at the moment.

**Comment by github-aji** [comment]
> Can I ask what's the reason for putting strict firewall rules on a bunch of static files?
This firewall rule is applicable for all the apps deployed on our account . Generally we whitelist the ip ranges , if we want to give third party access to our lower environments.

**Comment by github-aji** [comment]
@emmenko ,
Please let me know if you have any update on this .

**Comment by emmenko** [comment]
Hi, I don't have an update so far. We'll get back to you as soon as we can.

**Comment by emmenko** [comment]
Hi @github-aji , we discussed this internally and we'll reach out to your team privately.

**Comment by tdeekens** [comment]
Thanks for the in person discussion. This is, as promised, an example how Sentry allows to specify a custom header.

<img width="1302" alt="Screenshot 2020-07-09 at 10 24 04" src="https://user-images.githubusercontent.com/1877073/87016192-ab532c80-c1ce-11ea-87a4-354fefeb1d95.png">

This is nothing we support yet and would have to be aligned with the Product Team as to feasibility and timeline. Again, this comes with its own pitfalls. Specifially that the value needs to be shared and in-sync with us and you at all times. Personally, I would still recommend to remove/move the mc-http-server out of the protected parts of the environment or deploy the Custom Application to Vercel.
