### ISSUE TITLE
Allow ReactNode as a title prop on info-dialog component

### ISSUE THREAD

**Issue by dogayuksel** [commercetools/merchant-center-application-kit#1864]
**Is your feature request related to a problem? Please describe.**

Info-dialog component only accepts string type as a title. Throws type errors when we pass in a ReactNode as seen below which is a combination of some string and a stamp from ui-kit.

<img width="148" alt="Screenshot 2020-11-11 at 10 00 11" src="https://user-images.githubusercontent.com/1379086/98791011-bdefa380-2404-11eb-9cd5-8c152730b649.png">

**Describe the solution you'd like**

We would like to change type of title from string to a ReactNode.

This would consequently affect the following components and respective props:

> DialogHeader :: title
> DialogContainer :: title
> Modal :: contentLabel
> ModalPortal :: contentLabel

**Additional context**

Here is how the info dialog looks like when we use a ReactNode for the title:

<img width="1435" alt="Screenshot 2020-11-11 at 09 56 52" src="https://user-images.githubusercontent.com/1379086/98791559-86352b80-2405-11eb-9919-4f48fa0f941e.png">

**Comment by emmenko** [comment]
Thanks for idea. The main issue I see with this is that we use the string value for accessibility purposes.
Changing it to a React node would make it hard/impossible to keep the same behavior.

I feel like this requires also some decision from the design team. For example, we shouldn't allow to any value.

If the only use case so far is to have a stamp-like text next to the title, then I would prefer to have a dedicated prop for that, so that only a stamp can be rendered.

**Comment by tdeekens** [comment]
Maybe a title and a stamp prop could do the trick?

**Comment by islam3zzat** [comment]
Adding a **stamp** prop should do the trick for this use-case, alternatively, we could add **contentLabel** prop and this one gets used for accessibility, and the **title** prop gets used as the title.

We currently pass the **title** prop to two components

- **DialogContainer** https://github.com/commercetools/merchant-center-application-kit/blob/9e6ffae509d121619631803df29ed444147162c2/packages/application-components/src/components/dialogs/info-dialog/info-dialog.tsx#L22

- **DialogHeader** https://github.com/commercetools/merchant-center-application-kit/blob/9e6ffae509d121619631803df29ed444147162c2/packages/application-components/src/components/dialogs/info-dialog/info-dialog.tsx#L25


The one passed to the **DialogContainer** gets forwarded  to the react-modal's Modal and it gets used for accessibility and it has to be a string.

The one passed to **DialogHeader** gets rendered for that either string or component should work fine.

**Comment by emmenko** [comment]
This is one reason yes. The other reason is that we most likely don't want to allow ANY component/node to be rendered in the title, thus having a strict structure of what can and should be rendered (UX/UI consistency).

**Comment by tdeekens** [comment]
While upgrading to the new JSX runtime internally I noticed that we have about 5-6 locations where we overwrite `console.error` to suppress errors caused by this. 

Either we:

1. Wait for the `New`-stamp to eventually be removed 🤔  
2. Add another prop for the `stamp` to be rendered more explicitly 
3. Add another prop for the accessibility label

I somewhat think it's fine by UX/UI to potentially bring up the requirement or rendering an icon in the modal's header. Maybe not often but conceptually it doesn't sound unusual to me.

**Comment by mmaltsev-ct** [comment]
@FilPob, need your input here. Could you take a look at the issue please and see what could be the best option from the UX perspective, please?

**Comment by jaikumar-tj** [comment]
JFYI @FilPob The Pacman team also recently added the `New` tag to this info-dialog that explains the new feature to the customer. Even though the component throws a warning when I pass the stamp component but in the UI, it looks proper.
https://commercetools.atlassian.net/browse/PCM-3483?focusedCommentId=669129
<img width="544" alt="Screenshot 2024-01-02 at 09 04 48" src="https://github.com/commercetools/merchant-center-application-kit/assets/83634106/71815bba-1bc1-481d-a6db-a72d222c00e8">
