### ISSUE TITLE
Type error when using useShowNotification

### ISSUE THREAD

**Issue by ahmehri** [commercetools/merchant-center-application-kit#1870]
**Describe the issue**

A type error occurred when using `useShowNotification`.

**To Reproduce**

Example code:

```js
const showNotification = useShowNotification();
showNotification({
  kind: 'success',
  domain: DOMAINS.SIDE,
  text: 'My text',
});
```

**Expected behavior**

Because the passed object is of type `Notification extends TShowNotification`, I don't expect any typing error. However, the following error occurred.

```
Argument of type '{ kind: "success"; domain: "side"; text: string; }' is not assignable to parameter of type 'TShowNotification'.
  Object literal may only specify known properties, and 'text' does not exist in type 'TShowNotification'.ts(2345)
```

**Screenshots**

<img width="589" alt="Screenshot 2020-11-13 at 16 16 35" src="https://user-images.githubusercontent.com/3668245/99088004-b8908580-25cb-11eb-8eb8-1e4459c1ad82.png">

**Additional context**

**Comment by adnasa** [comment]
Hey thanks for reporting.
Are these warning related to the v17 migration or later version?
this is to help back track the problem.

**Comment by ahmehri** [comment]
If I remember correctly, the problem occurred even before the v17 migration and I think it's not related to it.

**Comment by adnasa** [comment]
I had a look into this.
It will require a slight change on the signature of `useShowNotification` and the callback.

**Comment by emmenko** [comment]
Thanks for reporting.

This is a known issue yes, it's a bit tricky though.

If someone wants to look into it, feel free.

**Comment by adnasa** [comment]
> If someone wants to look into it, feel free.

I did 😅  and I realised the same. it's tricky and will need to change the `addNotification` signature, I think.
can step in here when I can

**Comment by emmenko** [comment]
To be more clear, when using `useShowNotification` you need to pass the type parameter `Notification extends TShowNotification`.

The type `TShowNotification` does not include `text` because it's not really a concern of the `actions-global` package

https://github.com/commercetools/merchant-center-application-kit/blob/89c4464c334dd6c3922d031872286ad3bea8cf67/packages/actions-global/src/types.ts#L11-L14

The `text` is actually only used in the `react-notifications` package

https://github.com/commercetools/merchant-center-application-kit/blob/89c4464c334dd6c3922d031872286ad3bea8cf67/packages/react-notifications/src/components/notifier/notifier.tsx#L17

Maybe we can simply declare the `text` as optional in the `TShowNotification`, or we should provide more detailed pre-built types.

**Comment by adnasa** [comment]
>  we can simply declare the text as optional in the TShowNotification

I'm fine with pushing a commit to extend this TShowNotification

**Comment by adnasa** [comment]
@ahmehri #1879 is merged in.
once this PR (#1878)  is merged in,
you can try to update your project and see if the errors disappears

**Comment by ahmehri** [comment]
I tested it and I got this error.

```
Argument of type '{ kind: "info"; domain: "side"; text: string; }' is not assignable to parameter of type 'TShowNotification'.
  Property 'id' is missing in type '{ kind: "info"; domain: "side"; text: string; }' but required in type 'TNotification'.ts(2345)
```

which was solved once I added the `id`.

```diff
imageNotificationBeforeUploadHandler = showNotification({
+ id: 1,
  kind: 'info',
  domain: DOMAINS.SIDE,
  text: intl.formatMessage(
    productDetailsMessages.imageUploadNotification,
    {
      count: imagesToUpload.length,
    }
  ),
});
```

which means the fix worked, thanks!

Any ideas what this `id` is for? Is it ok to provide a random value? Should I be worried about collision?

**Comment by emmenko** [comment]
You shouldn't provide the id.

**Comment by emmenko** [comment]
The problem is with the generic type parameter. If you use TS, the signature requires to provide a type parameter that inherits the shape of a `TShowNotification`.

Obviously you can't provide a type parameter in a JS file, as you get a syntax error.

What we can do is to default the type parameter to `TShowNotification`

```js
Notification extends TShowNotification = TShowNotification
```

**Comment by ahmehri** [comment]
See https://github.com/commercetools/merchant-center-application-kit/issues/1870#issuecomment-728837085.

**Comment by mmaltsev-ct** [comment]
Couldn't reproduce the issue after the recent updates. @ahmehri please reopen the ticket if you encounter this problem again.
