### ISSUE TITLE
Extract `test-utils` out of `application-shell`

### ISSUE THREAD

**Issue by adnasa** [commercetools/merchant-center-application-kit#1927]
**Is your feature request related to a problem? Please describe.**

The status quo is that we expose `renderApp{WithRedux}` from the `application-shell`.
Although fair, this increases the dependency towards the `application-shell` as a package, although it doesn't have to.

**Describe the solution you'd like**

Extract the `application-shell/test-utils` into its own package.

**Describe alternatives you've considered**

**Additional context**

The consumer is aware that using `renderApp{WithRedux}` implies that the `application-shell` (along with connectors and providers) wraps the component that they want to test. This doesn't mean however that `application-shell` is the right location for the test utils.

What the `test-utils` really is, is a wrapper of ApplicationContextProvider, Apollo and the Application Shell built on top of RTL to ease testing of apps connected to the Merchant Center.

That constitutes as a good candidate to be its own package.

Marking this as a potential change, because consumers needs to migrate and update their imports.

**Comment by emmenko** [comment]
To clarify. The test-utils should still be in appshell, because most of the stuff relates to testing an application, and it also requires internal stuff from the appshell package.

What we should be looking into, is to see if we can extract some functionality that does not rely on the appshell directly.

For example, to test the picker component we only need to have an application context.

**Comment by emmenko** [comment]
I don't think we can do anything about this. The picker is also moved to another repo, so we shouldn't have this problem anymore.

Feel free to reopen this if you still see a need to do some work here.
