### ISSUE TITLE
Authorization Required When Clicking on Custom Application Icon?

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2051]
**Description**

i just registered a custom application to test it, but when i click on the menu item i get an authentication prompt where i have to enter credentials which i don't have (i think).  My MC credentials don’t work when entered here either. I tried that as a first attempt to solve the issue on my own.

Is a custom application required to implement permissions, even when they’re not applied/checked in the application?

**Expected behavior**

Clicking the Custom Application icon in the MC should launch the app.

**Comment by emmenko** [comment]
Hi, the prompt is caused by your server where the Custom Application is (apparently) running.

<img width="837" alt="Screenshot 2021-02-10 at 16 45 25" src="https://user-images.githubusercontent.com/1110551/107533867-a8cf1000-6bbf-11eb-8c2e-5cfea65d2c2f.png">

This is the URL that has been registered with the application.

Also, a couple of other things I noticed:
* Please use `https`!
* You should change the entry point URI path from `examples-starter` to something unique and more meaningful to your application. https://docs.commercetools.com/custom-applications/getting-started/installing-a-starter-application#renaming-the-application-main-route-path
