### ISSUE TITLE
Make <Notification> accessible

### ISSUE THREAD

**Issue by ahmehri** [commercetools/merchant-center-application-kit#2059]
**Is your feature request related to a problem? Please describe.**

Currently, closing notifications in tests is not ideal, we need to click on the close icon by selecting it using the following selector

```js
screen.getByLabelText(/Hide notification/i);
```

This is not ideal when we have more than one notification in the test, if I want to close the second notification, for example, I need to select the related close icon.

```js
screen.getAllByLabelText(/Hide notification/i)[1];
``` 

It's clear that the above selector is brittle and that the test will fail once the order of notifications changes.

**Describe the solution you'd like**

I would like to be able to select the close icon by first selecting the actual notification. This can be done by adding the a11y role `alertdialog` to the wrapper DOM element. `aria-describedby` property should be used, according to the [specification](https://www.w3.org/TR/wai-aria-1.1/#alertdialog), to reference the alert message element in the dialog.

```js
<div role="alertdialog" aria-describedby="content">
  <div id="content">{props.children}</div>
  {/* ... */}
</div>
```

The close icon can then be selected as follows.

```js
within(screen.findByRole('alertdialog', { description: /the message of the notification/i }).getByLabelText(/Hide notification/i);
```

**Describe alternatives you've considered**

I've considered using the role `dialog` but I ended up suggesting `alertdialog` instead because the latter is more suitable for the use case. A notification is [at the end](https://www.w3.org/TR/wai-aria-1.1/#alertdialog):

> A type of dialog that contains an alert message, where initial focus goes to an element within the dialog. See related alert and dialog.

**Additional context**

I tried to implement the proposed solution and I faced two challenges:

- The ID of the DOM element whose content will be the notification message should be unique. Otherwise, the selection won't be precise, in the above example of selecting the second notification, the result will be that the first notification is selected instead. I think this can be solved by passing a new prop `name` to the component and append it to the ID, `content-${name}`.
- The `ByRoleOptions` type of `@testing-library/dom` only supports the property `name` when selecting an element. I ignored the type warning and used `description` anyway and it worked, but still having the type warning is a problem. I also checked and couldn't find a way to set the name of an `alertdialog`.

```
// no type warning but it doesn't work
screen.findByRole('alertdialog', { name: /the message of the notification/i });

// type warning but it works
screen.findByRole('alertdialog', { description: /the message of the notification/i }
```

**Comment by emmenko** [comment]
>  I think this can be solved by passing a new prop `name` to the component and append it to the ID, `content-${name}`.

I would simply generate a "random" identifier, like we do for input fields with sequential numbers. No need to pass an extra prop.

> The `ByRoleOptions` type of `@testing-library/dom` only supports the property `name` when selecting an element.

I think it works simply because `description` is [ignored](https://github.com/testing-library/dom-testing-library/blob/c6acb0a3775f841dbce9db5388c172d03daf7a80/src/queries/role.js#L27-L40), so it only matches the role `alertdialog`. Assuming that there is only one `alertdialog` visible at a time, maybe that's enough to use `findByRole('alertdialog')`.

**Comment by CarlosCortizasCT** [comment]
Hello :wave:

I’ve been looking into this issue again and I think we have two _problems_:
* Make the component accessible so assistive technology (eg: screen readers) can precisely notify about the notification being displayed.
* Allow closing a specific notification from React Testing Library written tests (when we rendered several of them in a test case).


I think the first one should be tackled by implementing what @ahmehri explained about using *alertdialog* role for the component container and link the message to it us gin the *aria-describedby* attribute as it’s mentioned in the [documentation](https://www.w3.org/TR/wai-aria-1.1/#alertdialog).
Bear in mind that using that attribute is not mandatory and that we should set the focus inside the notification (it’s expected to be in the close button for simple notifications).

The second problem currently is a little more complex because, as @emmenko explained, RTL does not currently support filtering `*ByRole` queries by description but only by name.
[This](https://github.com/testing-library/dom-testing-library/blob/c6acb0a3775f841dbce9db5388c172d03daf7a80/src/queries/role.js#L1) is the file implementing `*ByRole` queries and it uses the function `computeAccessibleName` to resolve the results when filtering by name.
Curious thing is that there is another function in the same package ([dom-accessibility-api](https://github.com/eps1lon/dom-accessibility-api#dom-accessibility-api)) which helps resolving by description but they don’t use it in RTL.
One option could be to ask or even contribute to RTL to implement filtering by description similar of what has been done a couple of years ago with _name_ filtering ([this is the PR](https://github.com/testing-library/dom-testing-library/pull/408)).

I think @ahmehri proposal of having a new property to be used as the id to link the notification container to its message is a fair solution. We could also have it as an optional property and use an autogenerated ID (as @emmenko proposed) as fallback so we guarantee we always have correct _aria_ values.
My main concern here is that `Notification` component consumers would be able to provide the same value for this new property for different notifications which would break the accessibility _linking_ so assistive technologies could end up providing incorrect information.

My vote here would be to first implement the aria attributes with a private autogenerated ID in the `Notification` component and ask RTL team to implement *description* filtering ability to `*ByRole` queries (or work ourselves in contributing if we are allowed to).
The current situation makes the tests inconvenient but not impossible and I think it’s more important for the component to at least have the right attributes for assistive technology to properly deal with it.

Reference:
* [RTL docs](https://testing-library.com/docs/queries/byrole)
* [`alertdialog` spec](https://www.w3.org/TR/wai-aria-1.1/#alertdialog)
* [What is an accessible name?](https://www.tpgi.com/what-is-an-accessible-name/)
* [Accessible Name and Description spec](https://www.w3.org/TR/accname-1.1/)

**Comment by emmenko** [comment]
Thanks, sounds like a plan.

We can very much contribute to other projects yes. If you feel like it, go ahead and propose it or open a PR in the RTL project.

**Comment by CarlosCortizasCT** [comment]
I created [this PR](https://github.com/testing-library/dom-testing-library/pull/1120) in **dom-testing-library** project to allow filtering `ByRole` queries using an accessible description.

**Comment by CarlosCortizasCT** [comment]
So the PR was accepted and already merged into main.

It will available once they release their next version.

**Comment by emmenko** [comment]
Ah wow, that was fast. Thanks for contributing! 🎉

**Comment by CarlosCortizasCT** [comment]
The [latest published](https://github.com/testing-library/dom-testing-library/releases/tag/v8.13.0) version of `dom-testing-library` already includes the new filter option for `*ByRole` queries.

Since the version we use for `@testing-library/react` (**12.1.4**) has a [flexible range](https://github.com/testing-library/react-testing-library/blob/v12.1.4/package.json#L48) for the other one, I think we can already use it.
