### ISSUE TITLE
Unable to run mc-scripts compile-html

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2090]
**Describe the issue**

I am unable to run the mc-script from my machine documented here:

https://docs.commercetools.com/custom-applications/development/available-scripts#top

When I run the command, "mc-scripts compile-html", I receive the error "bash: mc-scripts: command not found"

![image](https://user-images.githubusercontent.com/29213153/110344102-2c332400-7ffb-11eb-8008-c2b2089e6acf.png)

I am running Node v14.16.0
I am running NPM v6.14.11

**To Reproduce**

1. Install package as documented here:  https://docs.commercetools.com/custom-applications/development/available-scripts#top
2. Run command 'mc-scripts compile-html'
3. Observe error, "bash: mc-scripts: command not found"

**Expected behavior**
When running package, mc-scripts command should be found

**Comment by emmenko** [comment]
If you run the command directly, you need to reference the binary. You can do that with `yarn <command>`, so `yarn mc-scripts compile-html`.

Otherwise define the command in the `package.json` scripts (for example https://github.com/commercetools/merchant-center-application-kit/blob/075c770a009c9f428a83a6c57f924b7683bef0fc/application-templates/starter/package.json#L7). Then you can run `yarn build`.

You could also install the `mc-scripts` package globally, but we don't recommend that.

**Comment by tdeekens** [comment]
From where (what directory) to you run the script? The `mc-scripts` binary is an NPM binary and hence it is not globally available on your system but only from within (the directory) of you custom application.
