### ISSUE TITLE
CT favicon for new MC URL not shown properly

### ISSUE THREAD

**Issue by YahiaElTai** [commercetools/merchant-center-application-kit#2101]
**Describe the issue**
Since we changed from the old MC URL to the new one, the favicon (icon in the browser) is not displayed correctly for every MC user. It is not clear what the problem is here, as it differs from user to user. Instead of the Commercetools cube, the world icon is displayed.

**Background**:
Legacy hostname → New hostname
mc.commercetools.co → mc.us-central1.gcp.commercetools.com
mc-api.commercetools.co → mc-api.us-central1.gcp.commercetools.com
mc.commercetools.com → mc.europe-west1.gcp.commercetools.com
mc-api.commercetools.com → mc-api.europe-west1.gcp.commercetools.com

**Expected behavior**
The favicon should be displayed correctly for all MC users.

**Screenshots**
**Current behavior**
<img width="650" alt="Bildschirmfoto 2021-03-03 um 14 49 46" src="https://user-images.githubusercontent.com/30247059/111138084-d3760500-857f-11eb-83e4-49ae3f265c04.png">

**Comment by tdeekens** [comment]
Spend a couple of minutes investigating. This is what I found out.

In Chrome (which I use a lot daily) it works:

<img width="661" alt="CleanShot 2021-03-16 at 09 29 58@2x" src="https://user-images.githubusercontent.com/1877073/111279291-d71a9200-863a-11eb-9069-83e7ae28df46.png">

Using Firefox shows it doesn't work. This is how the favicon is referenced.

<img width="1479" alt="CleanShot 2021-03-16 at 09 31 28@2x" src="https://user-images.githubusercontent.com/1877073/111279368-ec8fbc00-863a-11eb-9ec7-71ed28c4d39b.png">
<img width="680" alt="CleanShot 2021-03-16 at 09 31 37@2x" src="https://user-images.githubusercontent.com/1877073/111279373-ee597f80-863a-11eb-8801-98bce4e178ea.png">

Opening the url shows it actually doesn't load the favicon but redirects to the MC. 

<img width="1071" alt="CleanShot 2021-03-16 at 09 33 58@2x" src="https://user-images.githubusercontent.com/1877073/111279454-029d7c80-863b-11eb-8435-31e7154fa07b.png">

This means for me as a conclusion:

1. In browsers which have the favicon cached since weeks/months it works
2. In browsers without a warm cache it doesn't work
3. The favicon static asset(s) fail to load for some time now
    - I think they're meant to be in the Google Storage Bucket not exposed using the public url

I tried to find the favicons in the Google Storage Buckets but couldn't. What this means for possible solutions (I assume):

1. We need to upload the favicon to every environments Google Storage Bucket and reference it properly
2. We could inline it as base64 (downsides for caching and it can't be env specific easily then)

**Comment by tdeekens** [comment]
> Since we changed from the old MC URL to the new one

To conclude, I don't think this is the reason actually. At least I can't come to an understanding how it could be. Maybe I am missing something.

**Comment by emmenko** [comment]
It looks indeed that we don't upload some of the static assets...I guess this is more of an issue with our setup.

**Comment by emmenko** [comment]
I'm looking into it and will open a PR to fix it.

**Comment by tdeekens** [comment]
> It looks indeed that we don't upload some of the static assets...I guess this is more of an issue with our setup.

Yes but that's also half of the story. If you look at the serve module it explicitly maps to the favicon. If we'd upload it we'd also either map it in our proxy or change the path to it. Changing the path to it is also a change here I presume.
