### ISSUE TITLE
Proxy to External API

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2133]
**Describe the issue**

When trying to use the Proxy to External API, does it only supports https, or is http also allowed?

So far when I try to use an http endpoint it instantly get back 500 Internal Server Error without my service ever receiving a request.

Also documentation on how to use this without SDK's would be greatly appreciated.

https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api

(SUPPORT-11910)

**Comment by emmenko** [comment]
> does it only supports https, or is http also allowed

At the moment the proxy expects to forward HTTPS origins. What would be your use case for using HTTP? Could you describe it?

> So far when I try to use an http endpoint it instantly get back 500 Internal Server Error without my service ever receiving a request.

That's expected because at the moment we don't forward requests with HTTP protocol, only HTTPS.

> Also documentation on how to use this without SDK's would be greatly appreciated.

Can you be more specific? Which SDK are you talking about?

If you mean to make the HTTP request, the equivalent with curl would be something like this:

```
curl 'https://mc-api.europe-west1.gcp.commercetools.com/proxy/forward-to' -v \
  -H 'cookie: mcAccessToken=<token>' \
  -H 'x-forward-to: <url_to_forward_to>' \
  -H 'x-project-key: <project_key>' \
  -H 'content-type: application/json' \
  -H 'accept: application/json' \
  -H 'accept-version: v2'
```

Where `<url_to_forward_to>` is the "external API" URL you want to connect to.

---

As for the error message, we'll see if we can return a more user friendly message from the MC API.

**Comment by SGChristianMP** [comment]
Thank you, this answers my question.

> At the moment the proxy expects to forward HTTPS origins. What would be your use case for using HTTP? Could you describe it?
Simply for test purposes, I'm building an API and haven't exposed it through HTTPS as I'm still simply debugging.

I don't assume self-signed certificates will work?

**Comment by emmenko** [comment]
I see, thanks. For local development the best way we recommend (for now) is to use a local tunnel with something like ngrok. See https://github.com/commercetools/merchant-center-application-kit/issues/2128#issuecomment-814197613
