### ISSUE TITLE
adapt createSessionAuthVerifier for aws api gateway http api

### ISSUE THREAD

**Issue by pavvell** [commercetools/merchant-center-application-kit#2147]
Hi! we're using this library `@commercetools-backend/express` to verify requests coming from custom applications. it works on express apps, but does not work when used in combination of `aws api gateway + lambda` (exact example of using it in google cloud function https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#usage-for-serverless-functions does not work in aws)

**the cause**: request object in lambda does not have `url` and `originalUrl` fields. 

our current workaround it this:
```
request.originalUrl = request.rawPath + (
    request.rawQueryString 
      ? `?${request.rawQueryString}`
      : ''
  );
```

would be great to have this check built in in the library.

**Comment by pavvell** [comment]
@emmenko sure, here it is https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html 

it's an [http api](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html), not their [rest api](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-rest-api.html). I'm not sure if the problem also exist with rest api, we did not test it, but may be issue is relevant there too.

**Comment by CarlosCortizasCT** [comment]
Hello @pavvell 👋 

We've just released a [new version](https://github.com/commercetools/merchant-center-application-kit/releases/tag/%40commercetools-backend%2Fexpress%4021.1.1) of the @commercetools-backend/express package where we addresses the problem you found using it in a AWS Lambda functions environment.

Instead of adding some rules to handle that environment, we added a new property to the verifier factory so you can provide a helper function to resolve the URL from the request-like object received by your handler.

You can find more information in our updated [documentation](https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#usage-for-serverless-functions).

Thanks!
