### ISSUE TITLE
Replace Query Component with useQuery Hook in Data Fetching / Graphql API Requests Section

### ISSUE THREAD

**Issue by dogayuksel** [commercetools/merchant-center-application-kit#2221]
**Which part of the documentation does it affect and which topic does it refer to?**
[Request to graphql api section](https://docs.commercetools.com/custom-applications/main-concepts/data-fetching#requests-to-graphql-apis)  in data fetching documentation uses [deprecated Query Component](https://www.apollographql.com/docs/react/api/react/components/).

**Describe what needs to be improved**
We should rewrite the example using [useQuery hook](https://www.apollographql.com/docs/react/api/react/hooks/) considering the direction apollo-client and Merchant Center is going towards.

**Comment by CarlosCortizasCT** [comment]
Hi @dogayuksel,
Thanks for pointing out this outdated example.

We have a new Custom Applications documentation version since we published version 21 and we updated the "Data Fetching" section to actually use the `useQuery` hook [in the examples](https://docs.commercetools.com/custom-applications/development/data-fetching).

Do you think is good enough now?
