### ISSUE TITLE
Custom App deployment to azure failure with out of memory error

### ISSUE THREAD

**Issue by briantomkins** [commercetools/merchant-center-application-kit#2270]
Support-12732
**Error**
We are getting the following error while deploying the custom application in US region.

0: ExitFrame [pc: 0x346317dbe1d]
Security context: 0x16cacd49e6c1 <JSObject>
1: split [0x16cacd4906a1](this=0x3a9504202201 <Very long string[534444]>,0x08aaa0db4901 <String[1]\: \n>)
2: /* anonymous /(aka / anonymous */) [0x2086ee682201] [/azureagent/azureagentservice-1/azagentservice/_work/56/s/node_modules/webpack/node_modules/webpack-sources/lib/applySourceMap.js:~74] [pc=0x3463256bd36](this=0x0de8634826f1 <undefined>,chu...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

<img width="949" alt="deployment_issue" src="https://user-images.githubusercontent.com/46489759/122866221-efe9c080-d36a-11eb-8812-08605c39d751.PNG">

**Comment by tdeekens** [comment]
Hi, thanks for the issue. This happens when invoking something on `mc-scripts` on CI? First assumption is that this is more something to the hosting system and the backing VM running out of memory than the tool itself. If so, not sure what we can do. You could look into increasing the memory of Node.js. However, that's not something usually needed.

**Comment by emmenko** [comment]
Closing, assuming this is not an issue anymore.

If you have further questions:
* You can re-open this issue.
* You can open a GitHub discussion.
