### ISSUE TITLE
TS version of the starter kit

### ISSUE THREAD

**Issue by pavvell** [commercetools/merchant-center-application-kit#2297]
Current custom application starter kit is available only in JS, would be good to have a TS version of it, as all core libraries as I understand already have declaration files (as was mentioned in #1668)

current starter kit: https://github.com/commercetools/merchant-center-application-kit/tree/main/application-templates

**Comment by emmenko** [comment]
Hi @pavvell ,

Thanks for reaching out and for the interest in using TS.

Technically it's already possible to use TS. However, some uikit components are not fully migrated to TS yet, thus missing the type declarations. In this case, you would need to provide the type declarations on your own (you can see an example here https://github.com/commercetools/merchant-center-application-kit/tree/main/%40types).

We will have a starter kit available in TS once all core packages have type declarations, as otherwise it's confusing.

If you want though, you can already start developing the Custom Application using TS, as all the tools have TS support (mc-scripts, babel, eslint, etc.).

If you use Jest, take a look here: https://github.com/commercetools/merchant-center-application-kit/tree/main/packages/jest-preset-mc-app#typescript-support

Hope this helps you with the next steps. Don't hesitate to reach out if you need further help.
