### ISSUE TITLE
Addition of security headers for the custom applications necessity

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2306]
Following the documentation regarding deploying a custom application on the merchant center, we got to the step where it requires us to generate a lambda function to including security headers on all requests made to the CloudFront distribution.

See the relevant step of the provided documentation for context: https://docs.commercetools.com/custom-applications/deployment/example-deployment-aws-s3-cloudfront#update-aws-resources

After some tests, we realized that our generated custom application only loads from within the merchant center. Trying to loading it directly using the s3 bucket URL or the Cloudfront domain assigned to the s3 bucket, does not work. So we are interested to know what could potentially be the implications in terms of security if we do not add these security headers at all.

{{SUPPORT-13050}}

**Comment by emmenko** [comment]
Hi,

> After some tests, we realized that our generated custom application only loads from within the merchant center. Trying to loading it directly using the s3 bucket URL or the Cloudfront domain assigned to the s3 bucket, does not work.

Can you explain why you would want to load the Custom Application directly and not through the Merchant Center? Also, API requests and other things won't work outside of the MC domains.

> So we are interested to know what could potentially be the implications in terms of security if we do not add these security headers at all.

The security headers are obviously important and we strongly recommend to use them. Otherwise your application and data might be subject to XSS attacks and such.

However, I suppose the question about the security headers is related to not being able to access the URL directly? In which case, see answer to previous question.

**Comment by emmenko** [comment]
Closing, assuming this is not an issue anymore.

If you have further questions:
* You can re-open this issue.
* You can open a GitHub discussion.
