### ISSUE TITLE
MC custom application: Permission problem after migration app to @commercetools-frontend/* v21

### ISSUE THREAD

**Issue by cb-adesso** [commercetools/merchant-center-application-kit#2644]
Hello Support,

this is not bug request but more an migration support request. I'm currently using following guide https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications to migrate our custom application new required "Project-level Custom Applications". I'm mot sure how to proceed with my issue. Commercetools support adviced me to post here my issue. 

*Original ticket ID: SUPPORT-16848*

### General Information
* We use Admin user or DEV user with all permission active.
* Custom App is used for order managament task among other things.
* Logic is handled by REST Microservice hosted in AWS

### Migration Procress already done
* uninstall old custom application
* create custom application config
* update dependencies in package.json
** We moved from `@commercetools-frontend/* v18` to `@commercetools-frontend/* v21`
* adjust custom-application-config.json
* Update routes.js / constants.js in React as proposed by the guide

### Current Problem
* Custom Application crashes on access (open mc > click on > custom application > access denied permission not sufficient)
* Icon and menu is visible
* I changed value for `entryPointUriPath` in React, but 'access denied' turned only into 'crash error'.

### Relevant JS & Config files 
[package.json.txt](https://github.com/commercetools/merchant-center-application-kit/files/8909408/package.json.txt)
[custom-application-config.json.txt](https://github.com/commercetools/merchant-center-application-kit/files/8909415/custom-application-config.json.txt)
[routes.js.txt](https://github.com/commercetools/merchant-center-application-kit/files/8909422/routes.js.txt)
[constants.js.txt](https://github.com/commercetools/merchant-center-application-kit/files/8909437/constants.js.txt)

Any help is appriciated. 

Kind Regards,

Chris

**Comment by Rhotimee** [comment]
Hello @cb-adesso, 

I noticed you're using a different `entryPointUriPath` between the `custom-application-config.json` and `constants.js`. 

It seems you're using the project key instead of the actual entry point in your `constants.js` file, which is then used to compute the permissions you have in your `routes.js` file.

You would need to update your `constants.js` file to use the same entry point value you have configured in your `custom-application-config.json` file.

There are also some hints about how to reuse these values between those two files that can make it easier to avoid this kind of miss-configurations.
For instance, your config file could be a JS file instead of a JSON and then you could import the constant in it so you are sure both files use the same value.

You can read more about this in [this section](https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications#migrate-user-permissions) of the migration guide.

**Comment by cb-adesso** [comment]
Nice, using the correkt value for `entryPointUriPath` did resolve my permission problem. 
Now the app is missing `IntlProvider` in react ancestry, but this look more like regular React errors.
I think I can handle it.

Thank You!

**Comment by Rhotimee** [comment]
@cb-adesso, you can follow the suggestion in this [comment](https://github.com/commercetools/merchant-center-application-kit/issues/2648#issuecomment-1158600591) to resolve the IntlProvider issue
