### ISSUE TITLE
Issue with migration and React Intl: "Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry."

### ISSUE THREAD

**Issue by luddilo** [commercetools/merchant-center-application-kit#2648]
**Describe the issue**

I've followed the migration guide upgrading our custom-app to the new organisational level, including upping all packages to 21.x from 18.x.

Our app is breaking upon startup unless we wrap the ApplicationShell with an IntlProvider (from "react-intl"). Even doing so, though, upon errors the app breaks with the same error (see screenshot). 

**To Reproduce**

No idea. What do you propose?

**Expected behavior**

The error screen should show.

**Screenshots**

Error upon startup:
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/1072245/174074033-358985f1-32b9-4204-bb42-391b7ce74709.png">

Fix for startup error:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/1072245/174073519-9f9aa53c-ff4a-4669-ba78-e3ed62be614f.png">

Error on application-error:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/1072245/174073165-a63df3b5-1cf2-4149-ba77-784b3d6351df.png">

**Additional context**

Referred here by customer service: https://jira.commercetools.com/servicedesk/customer/portal/1/SUPPORT-16870

**Comment by mmaltsev-ct** [comment]
Hi @luddilo, thank you for submitting the issue. We need to do an investigation and will get back to you soon.

**Comment by Rhotimee** [comment]
Heyy @luddilo, 

I suspect multiple versions of `react-intl` in your dependencies. You can check that by running `yarn why react-intl` in the project's root directory.

If it is confirmed that there are different versions of `react-intl`, you could;
1.  Use [resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to override the other versions with the specified version.  

2. Run `yarn upgrade -R react-intl` which forces Yarn to Upgrade the  package to the latest version based on the specified range

Additionally, I suggest you upgrade `ui-kit` to the v15 since app-kit v21 uses that version. 

Please see other similar issues [2158](https://github.com/commercetools/ui-kit/issues/2158) and [2158](https://github.com/commercetools/ui-kit/issues/2158)

Let me know if this was helpful.

**Comment by luddilo** [comment]
Thanks @Rhotimee and @mmaltsev-ct. That indeed was the issue, we had 5.25.0 installed manually and 5.25.1 from the commercetools packages. Odd that this one patch version would cause that, but yeah, it did.
