### ISSUE TITLE
Issues with permissions for non-admin users when migrating custom applications

### ISSUE THREAD

**Issue by Lea97** [commercetools/merchant-center-application-kit#2725]
We are currently working on the migration of our custom application. We have followed all the required changes as in the docs and rolled the whole thing out to our dev instance on a test basis. As an admin user, I can still use the application as usual. 

We have now granted the normal users the permissions for the custom application. However, they do not seem to have the permissions that we configured for the custom application. Without configuring the rights again for the users, the custom application can no longer be used. The problem here mainly concerns the OrderEdits, for which no separate rights can be assigned.

Our expectation would be that a user group that owns the permissions for a custom application gets all the necessary permissions for it regardless of the other permissions the user owns. Now the question arises whether we are missing something during the migration or why the permissions for the custom application do not work.

**Comment by Rhotimee** [comment]
Hello @Lea97,

As explained in the [docs](https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications#migrate-user-permissions), the user permissions for Custom Applications are now decoupled from the default MC applications.
Hence, you can assign the custom app [permission](https://docs.commercetools.com/merchant-center/user-permissions) to the team instead of using that of the default MC application. Only users with the right permissions will be authorized.

If this isn't helpful, kindly provide your use case of using the old permission. So we can help you better.

**Comment by Lea97** [comment]
Hello @Rhotimee,

yes this is exactly the behavior we expect, but which does not seem to work after the migration. We have an application to process orders. For this we have configured the following for the permissions in our custom application config: 
```json
 "oAuthScopes": {
    "view": ["view_orders", "view_states", "view_shipping_methods", "view_order_edits"],
    "manage": ["manage_orders", "manage_order_edits"]
  }
```
The admin can use the custom application normally. If we now give another user group the View and Manage right for our custom application, they can open the application, but all queries within our application to Commercetools fail with a 403 Forbidden. This means, for example, that no list of orders can be queried, although this right should be included in the rights of the custom application.

**Comment by Rhotimee** [comment]
@Lea97, I believe you're not assigning the permissions to the team. Read how to do that [here](https://docs.commercetools.com/merchant-center/user-permissions#assign-permissions-and-action-rights-to-a-team)

**Comment by Lea97** [comment]
@Rhotimee, we have configured the permissions for the Custom Application as shown below:
![CustomApplicationPermissions](https://user-images.githubusercontent.com/28789519/180995405-b8b1f206-dcb2-47ce-bb28-930f9c728383.JPG)

We have a user group "User" to which we have given the rights of the custom application: 
![UserPermissions](https://user-images.githubusercontent.com/28789519/180994924-419fd52d-b9f9-4b36-bda9-ca5b89b1a242.JPG)

Now when I click on the Custom Application menu item and thus start the action that a table with orders in a certain state are queried, I get the following error message:
```
{"statusCode":403,"message":"Insufficient scope. One of the following scopes is missing: view_orders.","errors":[{"code":"insufficient_scope","message":"Insufficient scope. One of the following scopes is missing: view_orders."}],"error":"insufficient_scope","error_description":"Insufficient scope. One of the following scopes is missing: view_orders."}
```

**Comment by Rhotimee** [comment]
Hello @Lea97, 

We looked at the logs and couldn't find logs for only users on the users team.  The logs for the users we found are on the admin team.  To help further, we will require some information. Could you let us know which user is having the problem and share the information via a support ticket (because it is sensitive information)?

You could also try to sign out of the account and sign in again to generate a new token.

**Comment by Rhotimee** [comment]
@Lea97, We discovered the issue arose because you're using a custom HTTP client. When using a custom HTTP client, you must provide the necessary headers. 
We currently do not have proper documentation for this, but you can see the idea in #2553 

We found out about the issue by sending a request without the header `x-application-id` and got the `403` error. But, sending a request with the `x-application-id` header, the request was successful. See the screenshot below.

![image](https://user-images.githubusercontent.com/6726467/181533024-42d237ab-0d44-4432-a287-e09008384d69.png)

PS: The `x-application-id`  is currently optional for backwards compatibility, but it would be required after we end the migration period of project-level apps.


By the way, we would love to know the HTTP client you're using. 

Also, we noticed a 404 status code when loading the static files for the page even though it loads fine. This may have something to do with the rewrite rules for Microsoft Azure. It is advised that you look into it.

**Comment by emmenko** [comment]
The `x-application-id` can be defined using `window.app.applicationId`.

**Comment by Lea97** [comment]
Thank you very much for your feedback. We have now adjusted our API calls as described in the [doc](https://docs.commercetools.com/custom-applications/development/data-fetching#requests-to-rest-apis ). Now a normal user can use the application as expected. From our side, the ticket can be closed.

**Comment by Lea97** [comment]
Hey @emmenko,

we had previously used the JavaScript Fetch API.
