### ISSUE TITLE
Infinite reloads on deployed custom apps

### ISSUE THREAD

**Issue by Steven-Thelin** [commercetools/merchant-center-application-kit#2851]
I’ve migrated our three custom apps to v21. We’ve deployed these to our Azure staging environment, added the three applications to Merchant Center as well as mapped their respectful URL’s. However, opening any of the three custom apps just makes the page infinitely reload.

This doesn’t happen in the local development environment. An example of one of the custom apps that loops:
https://mc.europe-west1.gcp.commercetools.com/lakrids-by-blow-staging/order-management-org

**To Reproduce**
Steps to reproduce the behaviour:
Open any of the new custom apps in Merchant Center (I believe you have access to our MC?)

**Expected behaviour**

For it not to be stuck in a refresh loop

Please let me know what else you need to look into this. The code has been shared in the last issue where you guys politely helped me to get the custom apps to run locally.

**Comment by CarlosCortizasCT** [comment]
Hello @Steven-Thelin 

The issue might be related with a misconfiguration around the entry point URI path of the Custom Applications.

If you access the configuration for your Custom Application in the Merchant Center, you could check which entry point is configured for it. Example:
![image](https://user-images.githubusercontent.com/97907068/196877509-5423e426-3689-4f88-b5e3-cf9995ba3eee.png)

You need to make sure the value for that property is the same as you have in your Custom Application config file. The name of the property in the config file is [entryPointUriPath](https://docs.commercetools.com/custom-applications/api-reference/application-config#entrypointuripath).

Could you please double check the values match for your Custom Applications?

**Comment by Steven-Thelin** [comment]
Hi @CarlosCortizasCT 

The `entryUriPath` does already match the `entryUriPath` defined in the application 🙂

**Comment by CarlosCortizasCT** [comment]
Hi @Steven-Thelin 

I guess we will need extra info to try to figure out what's happening.

These are the points that could help us:
* Could you share the contents of your `custom-application-config` file? (obfuscate private information if any)
  * If you are using any environment variable, could you make sure they are defined when building the application?
* Is the redirection happening at server response level (eg: status code 30X) or the page loads and then it reloads because of some javascript code running?
* If the reload is triggered by javascript client-side, you might need to stop the redirection loop in the browser and inspect the dev tools console. Is there any error message? Could you inspect the property `window.app` and share with us its contents?

Thanks.

**Comment by Steven-Thelin** [comment]
Hi @CarlosCortizasCT ! Thanks for your response, and I'm sorry for the late reply.

`custom-application-config`
```
import { entryPointUriPath, PERMISSIONS } from "./src/constants";

const config = {
  entryPointUriPath,
  name: "Commerce Management",
  cloudIdentifier: "gcp-eu",
  oAuthScopes: {
    view: [
      "view_customers",
      "view_products",
      "view_states",
      "view_project_settings",
      "view_payments",
    ],
    manage: ["manage_orders"],
  },
  env: {
    development: {
      initialProjectKey: "lakrids-by-blow-staging",
    },
    production: {
      applicationId: "cl986j1g901i9ze011v7lpxgt",
      url: "${env:URL_ENV}",
      cdnUrl: "${env:CDN_URL_ENV}",
    },
  },
  headers: {
    csp: {
      "connect-src": [
        "lakrids-app-commerceapi-staging.azurewebsites.net",
        "lakrids-api-production-service.azurewebsites.net",
        "localhost:5000",
      ],
    },
  },
  additionalEnv: {
    authorizationHeader: "C58B2F50-AB91-4BD6-97E8-634949192219",
  },
  icon: "WorldIcon",
  key: entryPointUriPath,
  mainMenuLink: {
    defaultLabel: "Order Management (org)",
    uriPath: entryPointUriPath,
    permissions: [PERMISSIONS.View],
    featureToggle: null,
    submenu: [],
    labelAllLocales: [
      {
        locale: "en",
        value: "Order Management (org)",
      },
      {
        locale: "de",
        value: "Order Management (org)",
      },
      {
        locale: "es",
        value: "Order Management (org)",
      },
    ],
  },
};

export default config;
```
Env_vars are defined.

---

The redirection happens as soon as the page loads in Merchant center. It cannot be reproduced in localhost. It loops so fast that no console errors gets to see the light.

---

I tried intercepting the reload cycle, but no console errors were to be found.
`window.app` contents:
```
{
    "applicationName": "Stock Overview",
    "entryPointUriPath": "stock-overview",
    "cdnUrl": "https://lakrids-app-ordermanagement-staging.azurewebsites.net/stock-overview",
    "env": "production",
    "frontendHost": "mc.europe-west1.gcp.commercetools.com",
    "location": "gcp-eu",
    "mcApiUrl": "https://mc-api.europe-west1.gcp.commercetools.com",
    "revision": "",
    "servedByProxy": true
}
```

**Comment by CarlosCortizasCT** [comment]
Hi @Steven-Thelin,

Thanks for the information 👍 

It seems there is a mismatch with the `entryPointUriPath` with that application.
From the information you shared we can see the application finds the value `stock-overview` at runtime but the value configured in the Merchant Center for that application is another one (`order-management-org`).

The application reads this value at runtime from the `window.app` attribute which is generated at build time and added in the `index.html` file (you can check it in your build output folder: `public` by default).

You are setting the `entryPointUriPath` in your configuration file importing the value from your `constants` file, so I would suggest to check what value you have set in that latter file.

**Comment by Steven-Thelin** [comment]
@CarlosCortizasCT My bad, i sent the wrong info. We have three apps running that's almost identical.
But to compare the right page to the right source:

`constants.js` from `order-management`
```
import { entryPointUriPathToPermissionKeys } from "@commercetools-frontend/application-shell/ssr";

export const entryPointUriPath = "order-management-org";
export const PERMISSIONS = entryPointUriPathToPermissionKeys(entryPointUriPath);

export const FEATURE_FLAGS = {};

export const UPDATE_ACTIONS = {
  COLUMNS_UPDATE: "columnsUpdate",
  IS_TABLE_CONDENSED_UPDATE: "isTableCondensedUpdate",
  IS_TABLE_WRAPPING_TEXT_UPDATE: "isTableWrappingTextUpdate",
};
```

And in Merchant center:
![Screenshot 2022-10-24 at 13 27 12](https://user-images.githubusercontent.com/19597055/197515537-35b28c6c-e1b5-4952-97b8-f3b710d4e881.png)

The entry uri path looks identical to me, unless I really need glasses 😅

**Comment by CarlosCortizasCT** [comment]
Hi @Steven-Thelin 

So I loaded the `order-management` application in the browser (with JS disabled) so I can inspect the DOM and it seems the `entryPointUriPath` in missing in the `window.app` prop:
![image](https://user-images.githubusercontent.com/97907068/197517568-e0e69022-8baf-4a1a-9a88-39e7e6e12fdf.png)

Just to be sure, could you double check the version of the application deployed in your hosting provider is the latest one?

When you build the Custom Application, by default it generated its output in the `public` directory in your project's root folder. Over there, you can check the `index.html` file to find the script which sets the `window.app` property which should include the `entryPointUriPath` attribute. If that's correct, you would need to make sure you publish this to your hosting provider and that the Merchant Center has the right value for the "Application URL" value in the Custom Application configuration UI.

**Comment by Steven-Thelin** [comment]
@CarlosCortizasCT It turned out that the app wasn't ever deployed in Azure, only built. I'm now past the reload issue, so you were right all along 😄 

The issue is kind of different now. I'm bashing into a security issue. Is this something you know anything about?
![Screenshot 2022-10-24 at 15 11 04](https://user-images.githubusercontent.com/19597055/197533623-58c31ff1-1075-45b5-bc51-85b242e58eb1.png)

**Comment by CarlosCortizasCT** [comment]
Hi @Steven-Thelin 

That error comes from the [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) config we include in the HTML file at build time. Specifically the [script-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src) directive, which controls from what sources the browser can load script files.
(_take into account that the Custom Application is loaded from a commercetools domain_).

By default we include in this directive the application URL so we make sure the browser is allowed to fetch the scripts (and all the other assets) from your hosting provider.

Taking a look at the error you shared I can see the application URL which is included in the `script-src` directive is not what we expect it to be.
The current value is this one:
```
https://lakrids-app-ordermanagement-staging.azurewebsites.net/order-management
```
This is telling the browser only the file named `order-management` from the domain `lakrids-app-ordermanagement-staging.azurewebsites.net` is allowed to be loaded.

What we need is for that URL to have an ending backslash:
```
https://lakrids-app-ordermanagement-staging.azurewebsites.net/order-management/
```
Using this value we are telling the browser it can fetch anything `below` the directory `order-management` from the domain `lakrids-app-ordermanagement-staging.azurewebsites.net`.

This value in the CSP headers comes either from [cdnUrl](https://docs.commercetools.com/custom-applications/api-reference/application-config#envproductioncdnurl) or [url](https://docs.commercetools.com/custom-applications/api-reference/application-config#envproductionurl) properties of your configuration file.

I don't see which values you are using because you get them from environment variables, but I think you would need to update those to have the ending backslash and deploy your application again.

![image](https://user-images.githubusercontent.com/97907068/197565805-a8295aaa-8f98-4182-bf1f-184060c4a327.png)

**Comment by Steven-Thelin** [comment]
@CarlosCortizasCT Thank you, Carlos! I'll give it a try 🙂

**Comment by Steven-Thelin** [comment]
Thank You, @CarlosCortizasCT ! They all work as intended now.

I thank you for your patience and the support 🥳
