### ISSUE TITLE
Not able to fetch the Types data from GraphQL

### ISSUE THREAD

**Issue by satyam21041997** [commercetools/merchant-center-application-kit#2901]
I want to display the "Types" data in DataTable in Merchant Center custom application. I have added permission for that in "custom-application-config.mjs" and tried with "view_types" and "`manage_types`". But I am getting some error.

![image](https://user-images.githubusercontent.com/94686066/205275570-e189c65b-8b25-4ead-b448-402b3892e787.png)
![image](https://user-images.githubusercontent.com/94686066/205275583-c333a0dd-9ba3-4095-8313-bccc5751ec80.png)

I am attaching the configuration file. Could you please help me to correct the config file.
[custom-application-config.mjs.txt](https://github.com/commercetools/merchant-center-application-kit/files/10140390/custom-application-config.mjs.txt)

**Comment by CarlosCortizasCT** [comment]
Hi @satyam21041997 

Yes, to fetch types related information it is enough using the `view_types` oAuth scope.

The GraphQL query you previously shared seems also ok so perhaps it's a matter of targeting the right service in the context of the GraphQL request.

Here is an example using the `useMcQuery` helper:
```
const { data, error, loading } = useMcQuery(FetchTypesDefinitions, {
  variables: {
    limit: perPage.value,
    offset: (page.value - 1) * perPage.value,
    sort: [`${tableSorting.value.key} ${tableSorting.value.order}`],
  },
  context: {
    target: GRAPHQL_TARGETS.COMMERCETOOLS_PLATFORM,
  },
});
```

Since you already closed the issue, perhaps you already found the root cause of the problem you mentioned. If that's the case, maybe you can let us know about it so we can help other people having similar issues.

Thanks.
