### ISSUE TITLE
I want to call an external api from Custom application

### ISSUE THREAD

**Issue by satyam21041997** [commercetools/merchant-center-application-kit#3032]
Hi,
I want to use an external API created in Merchant Center Custom application. I tried 'fetch' and 'axios' in the application but it was not working.
![image](https://user-images.githubusercontent.com/94686066/230442131-945cabd9-779b-4b1f-9ae2-569157737aff.png)

Please help me on it.

**Comment by kark** [comment]
Hi,

Thanks for reaching out. 

We have very little details to be able to debug your case. 
Is this a deployed Custom Application accessed from the Merchant Center?
I am asking because this kind of error typically happens when your Custom Application is [misconfigured](https://docs.commercetools.com/custom-applications/api-reference/application-config#headerscsp) (please make sure that [`cloudIdentifier`](https://docs.commercetools.com/custom-applications/api-reference/application-config#cloudidentifier) and [`env.production.url`](https://docs.commercetools.com/custom-applications/api-reference/application-config#envproductionurl) are set correctly in your Custom Application config).

If that is not the case, please share more details of how you make requests to the `/proxy/forward-to` endpoint.

Thanks

**Comment by satyam21041997** [comment]
Hi @kark ,
Currently I am running Custom Application in Localhost server.

**Comment by CarlosCortizasCT** [comment]
Hello @satyam21041997 

We would like to double check you are aware fetching data from an external API in MC Custom Applications involves following [this flow](https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api) since the request needs to be proxied through the Merchant Center API.

If you are already using such an implementation, would you be so kind to provide a code example for a request that fails with that error, please?

Thanks!
