### ISSUE TITLE
[CustomApplication] Cannot find a function detail for custom hook useShowApiErrorNotification()

### ISSUE THREAD

**Issue by thientran-merkle** [commercetools/merchant-center-application-kit#3284]
Hi team, 

I’m following the custom application document to create the first application for the merchant center. 

Everything is working perfectly, but i’m facing an issue while transferring the form error to the useShowApiErrorNotification to show the message to the business user.

So i decided to check the function useShowApiErrorNotification to know how it works, but i cannot find any file to describe this function detail, only the typescript file to desclare it here:

node_modules/@commercetools-frontend/actions-global/dist/declarations/src/hooks/use-show-api-error-notification.d.ts

Can you help to teach me where the detail of this custom hook?

Regards,

Thien,

**Comment by CarlosCortizasCT** [comment]
Hi @thientran-merkle 

So that helper function exists in the @commercetools-frontend/actions-global package and you can find its signature description [here](https://docs.commercetools.com/custom-applications/api-reference/commercetools-frontend-actions-global#useshowapierrornotification).

Also, we have [this documentation](https://docs.commercetools.com/custom-applications/development/notifications#form-submitted-with-errors) where we explain in more detail how we suggest the errors can be shown to users.

Hope this helps.
