### ISSUE TITLE
Cannot start application locally in production mode

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#407]
**Describe the bug**
With #289 we changed how the navigation menu is loaded. For instance, in production the menu configuration is fetched from a `/api/graphql` endpoint on the same domain of the frontend app, as a we have a proxy router between the LB and the applications.

In development though, we usually start the app directly, without the proxy router. To render the menu config of the specific application, we load the menu config from a local file, skipping the graphql request (as the endpoint does not exist).

However, when testing the production build locally like so:

```bash
NODE_ENV=production mc-http-server --csp=$(pwd)/csp.json --config=$(pwd)/env.json --use-local-assets
```

the application starts in "production" mode, triggering the non-existing graphql request.

**Expected behavior**
It should be possible to start the application locally in production mode without having the graphql request to error.

**Additional context**
One solution would be to check for the flag `servedByProxy` from the `env.json`, which usually indicates if the application runs behind the proxy or not.

A bit unrelated to the problem, but we might also want to look into manually putting the menu data into the cache when we don't fetch from the graphql endpoint, so that we can still make the graphql query which will only read from the cache.

**Comment by ebonertz** [comment]
I am experience a similar issue here. I'm attempting to do a production build but getting this error. 

yarn build v1.0.2
(node:94943) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ mc-scripts build
Creating an optimized production build...
clean-webpack-plugin: /Users/ebonertz/Desktop/commercetools/mc-starter-app/mc-starter-app/dist has been removed.
[FinalStatsWriterPlugin] The dist folder could not be found at /Users/ebonertz/Desktop/commercetools/mc-starter-app/mc-starter-app/dist. Check the console for errors during the webpack compilation.
Failed to compile.

./src/components/entry-point/entry-point.js 43:19
Module parse failed: Unexpected token (43:19)
You may need an appropriate loader to handle this file type.
|           case 0:
|             _context.next = 2;
>             return import("../../i18n/data/".concat(lang, ".json")
|             /* webpackChunkName: "application-messages-[request]" */
|             );
 @ ./src/components/entry-point/index.js 1:0-40 1:0-40 2:0-51 2:0-51
 @ ./src/index.js
 @ multi ./node_modules/@commercetools-frontend/mc-scripts/config/polyfills.js ./node_modules/babel-polyfill/lib/index.js ./src/index.js


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I tried modify the env.json and setting servedByProxy as true. Am I missing something here?

**Comment by emmenko** [comment]
The `servedByProxy` should only be used in production environment.

As for the error, it seems that you are using an outdated version of the starter template. Can you compare your version with the one from master? (https://github.com/commercetools/merchant-center-application-kit/tree/master/application-templates/starter)

**Comment by tdeekens** [comment]
Sorry, but the given output is very hard to read. Can you maybe provide more concrete steps to reproduce the issue? What version of the starter are you on? Are you performing the steps provided [here](https://github.com/commercetools/merchant-center-application-kit/tree/master/application-templates/starter)?

From what I see the build fails. Did you run `yarn build` before running `yarn start:prod:local`? Does a simple `yarn start` yield another result? 

I just tried to reproduce but can't. I created a new custom app with the `create-mc-app`-cli both with just in dev-mode and prod-mode and both work fine for me.

Lastly, note that your yarn version is quite outdated in `1.0.2` with `1.15.2` being recent. It may not solve the issue but I recommend keeping it up-to-date to have installs being as similar/reproducable to our current `yarn.lock` as possible.

**Comment by ebonertz** [comment]
Thanks for the quick response guys. I updated yarn to the latest version now but same result. What is the best way to update the start app version without starting over? I've modified a lot of the code a long the way and don't want to overwrite it.

Up until I tried the build everything was working fine locally. This is the result I get from after running yarn build for the first time. When I run yarn start it gives the same error. 

Failed to compile.

./src/components/entry-point/entry-point.js 44:19
Module parse failed: Unexpected token (44:19)
You may need an appropriate loader to handle this file type.
```
case 0:
_context.next = 2;
return import("../../i18n/data/".concat(lang, ".json")
/* webpackChunkName: "application-messages-[request]" */
);
```

**Comment by tdeekens** [comment]
To my knowledge there is no build in `create-mc-app update` which also would be a bit hard to build. I know two options. Given that the starter is just a small wrapper with some boilerplate code using some of app-kits dependencies you can:

1. `yarn upgrade-interactive --latest`
   - to just use yarn to interactively pick and update deps
2. Backup anything in `/src/components/*` which is yours and create a new app and copy it in again

/cc @emmenko you know of any other ways?

**Comment by emmenko** [comment]
You should check the entry-point component and the `messages.js` file

**Comment by ebonertz** [comment]
@tdeekens I ran the yarn upgrade-interactive so all my dependencies are up to date now. That was magical. The build passed now. 

"Yarn start:prod:local" doesn't work for me and produces this output

```yarn start:prod:local
(node:97492) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error Command "start:prod:local" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

"Yarn start production product" produces this output :

```Compiled with warnings.
./src/components/entry-point/entry-point.js 54:19-56:13
Critical dependency: the request of a dependency is an expression
```

Will begin to the MC app but then a Sentry error occurs in the console. The loading wheel spins but the page doesn't load. I have attached a screenshot for your reference. There is definitely something going on the with entry-point.js file and the loadApplicationMessagesForLanguage function within it. 

![Screen Shot 2019-03-27 at 3 02 23 PM](https://user-images.githubusercontent.com/12550644/55105123-2fe56e80-50a2-11e9-9c6f-fb45babaf4f7.png)

**Comment by tdeekens** [comment]
1. yarn start:prod:local does not seem to exist in your outdated version of the starter
2. The loading of messages likely fails due to an updated babel

I would recommend taking it a step further and updating the non-moving (not yours) part of the starter too. It may be easer the other way around - not to pull/copy files in.Anyway you can do it in two ways I think

1. Create a new starter with an updated CLI for create-mc-app and copy your stuff in
2. Stay in your existing starter and check what changed (pkg.json, entry-point) and copy those over

Which way is quicker depends.

**Comment by emmenko** [comment]
Have you seen my message?

> You should check the entry-point component and the messages.js file

The problem you seem to have is around the i18n messages, which we fixed into the `messages.js` file. Please check that (and this commit here as reference: https://github.com/commercetools/merchant-center-application-kit/pull/477/commits/c75f60362a04bf09bd6ae3fb58f744050ab894e9)
