### ISSUE TITLE
Stagings and emotion source maps

### ISSUE THREAD

**Issue by montezume** [commercetools/merchant-center-application-kit#653]
#### Summary

Currently in our `babel-preset-mc-app`, and also in the babel preset for `ui-kit`, we remove source maps if the `node_env` is production.

More info about emotion source maps can be read [here](https://emotion.sh/docs/source-maps).

I think it's worthwhile to remove source maps in production. it leads to less data being sent down the wire to the user.

#### Problem

Some people use our staging environments for debugging the applications. I have talked to some designers who are used to being able to 'inspect element', and be able to change values. Now they are unable to do this. 

![can'tdoit](https://user-images.githubusercontent.com/2425013/58098744-7b1b8980-7bda-11e9-88e2-7cc0d97cbca2.gif)

#### Possible solution

Would it be feasible to have another node env? `staging`? And in this environment, ship the source maps? I guess it would lead to our circle environments have to do even more app building.

**Comment by tdeekens** [comment]
Why is removing source maps helping us at all? Which type of source map are we using? Inline? Then yes otherwise, if external source maps are used, I don't see why there is a harm in keeping them. They're loaded by a browser on demand when the dev tools are opened to my knowledge.

**Comment by montezume** [comment]
If I enable sourceMaps on ui-kit, we end up with a bundle size that is `2.5mb` vs `~750kb`. So it makes a pretty big difference. It's also not split. We would need to do some research into how we can split this in our build...

**Comment by tdeekens** [comment]
Yeah, seems to me like the rollup plugin only supports inline sourcemaps? https://github.com/maxdavidson/rollup-plugin-sourcemaps/blob/master/src/index.js

**Comment by tdeekens** [comment]
My expectation on this would be that sourcemaps are always generated as a filebased output. That doesn't affect bundlesize directly as they're loaded on demand and it's up to the consumer what to do with them. This is how the output of `@flopflip/react-broadcast` looks like: https://unpkg.com/@flopflip/react-broadcast@8.2.2/dist/. This would imply that we don't opt outof source maps in the babel-preset-mc-app during development but instead always generate them. I am not sure what the reason was to not have them generated. It makes sense if `babel-preset-mc-app` is used by an app but not if it's used by a library. Maybe it also calls for another option to overwrite the defaults `sourceMaps` which defaults to `isEnvDevelopment`.

**Comment by montezume** [comment]
Yeah, I couldn't find any information on splitting @emotion source maps out of the bundle.

**Comment by emmenko** [comment]
Hmm sorry but I don't think this is a problem with the sourcemaps. For starters, it looks like a problem related to the browser: on Chrome (screenshot left) it's disabled but on FF (screenshot right) you can interact with it.

<img width="1920" alt="Screenshot 2019-05-27 at 10 10 07" src="https://user-images.githubusercontent.com/1110551/58405417-a7feef00-8067-11e9-9e54-5bc785c58695.png">

Also, if you want to experiment with the styles, you can still do that in chrome (even though it's only applied to the element).

<img width="306" alt="image" src="https://user-images.githubusercontent.com/1110551/58405605-22c80a00-8068-11e9-9b6f-a8ef209e9521.png">

For those reasons, I don't see this as an issue, especially not with sourcemaps. I'll close this but we can still chat about it if I misunderstood something.
